from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(706, 655)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_answer_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_answer_1.setGeometry(QtCore.QRect(50, 140, 300, 200))
        self.btn_answer_1.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.btn_answer_1.setAcceptDrops(False)
        self.btn_answer_1.setStyleSheet("font: 14pt \"Open Sans\";")
        self.btn_answer_1.setCheckable(False)
        self.btn_answer_1.setAutoExclusive(False)
        self.btn_answer_1.setAutoDefault(False)
        self.btn_answer_1.setDefault(False)
        self.btn_answer_1.setFlat(False)
        self.btn_answer_1.setObjectName("btn_answer_1")
        self.btn_answer_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_answer_2.setGeometry(QtCore.QRect(360, 140, 300, 200))
        self.btn_answer_2.setStyleSheet("font: 14pt \"Open Sans\";")
        self.btn_answer_2.setCheckable(False)
        self.btn_answer_2.setAutoExclusive(False)
        self.btn_answer_2.setAutoDefault(False)
        self.btn_answer_2.setDefault(False)
        self.btn_answer_2.setFlat(False)
        self.btn_answer_2.setObjectName("btn_answer_2")
        self.btn_answer_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_answer_3.setGeometry(QtCore.QRect(50, 350, 300, 200))
        self.btn_answer_3.setStyleSheet("font: 14pt \"Open Sans\";")
        self.btn_answer_3.setCheckable(False)
        self.btn_answer_3.setAutoExclusive(False)
        self.btn_answer_3.setAutoDefault(False)
        self.btn_answer_3.setDefault(False)
        self.btn_answer_3.setFlat(False)
        self.btn_answer_3.setObjectName("btn_answer_3")
        self.btn_answer_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_answer_4.setGeometry(QtCore.QRect(360, 350, 300, 200))
        self.btn_answer_4.setStyleSheet("font: 14pt \"Open Sans\";")
        self.btn_answer_4.setCheckable(False)
        self.btn_answer_4.setAutoExclusive(False)
        self.btn_answer_4.setAutoDefault(False)
        self.btn_answer_4.setDefault(False)
        self.btn_answer_4.setFlat(False)
        self.btn_answer_4.setObjectName("btn_answer_4")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 20, 611, 81))
        font = QtGui.QFont()
        font.setFamily("Open Sans Light")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.btn_next_round = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.btn_next_round.setEnabled(False)
        self.btn_next_round.setGeometry(QtCore.QRect(320, 560, 71, 41))
        self.btn_next_round.setStyleSheet("")
        self.btn_next_round.setObjectName("btn_next_round")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 706, 21))
        self.menubar.setObjectName("menubar")
        self.menuMode = QtWidgets.QMenu(self.menubar)
        self.menuMode.setObjectName("menuMode")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionEn_Ru = QtWidgets.QAction(MainWindow)
        self.actionEn_Ru.setCheckable(True)
        self.actionEn_Ru.setChecked(False)
        self.actionEn_Ru.setObjectName("actionEn_Ru")
        self.actionRu_En = QtWidgets.QAction(MainWindow)
        self.actionRu_En.setCheckable(True)
        self.actionRu_En.setObjectName("actionRu_En")
        self.menuMode.addAction(self.actionEn_Ru)
        self.menuMode.addAction(self.actionRu_En)
        self.menubar.addAction(self.menuMode.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "EngTrainer"))
        self.btn_answer_1.setText(_translate("MainWindow", "First Translation"))
        self.btn_answer_2.setText(_translate("MainWindow", "Second Translation"))
        self.btn_answer_3.setText(_translate("MainWindow", "Third Translation"))
        self.btn_answer_4.setText(_translate("MainWindow", "Fouth Translation"))
        self.label.setText(_translate("MainWindow", "Слово для перевода"))
        self.btn_next_round.setText(_translate("MainWindow", "Next"))
        self.menuMode.setTitle(_translate("MainWindow", "Mode"))
        self.actionEn_Ru.setText(_translate("MainWindow", "En -> Ru"))
        self.actionRu_En.setText(_translate("MainWindow", "Ru -> En"))